name: Latest stack overflow activity
on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:
jobs:
    update-readme-with-stack-overflow:
        name: Update this repo's README with latest activity from StackOverflow
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                  max_post_count: "4"
                  comment_tag_name: "STACKOVERFLOW"
                  commit_message: "Updated readme with the latest stackOverflow data"
                  feed_list: "https://stackoverflow.com/feeds/user/9360885"
